dist: trusty
sudo: required
language: cpp
compiler:
- clang
- gcc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libpangomm-1.4-dev libcairomm-1.0-dev pkg-config

script:
- ./autogen.sh
- ./configure
- make
- VERBOSE=true make check
