os:
- linux
- osx

dist: xenial
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libpangomm-1.4-dev
    - libcairomm-1.0-dev
    - pkg-config
language: cpp
compiler:
- clang
- gcc

matrix:
  exclude:
  - os: osx
    compiler: gcc

install:
- if test -e scripts/travis/$TRAVIS_OS_NAME/$CC/install; then scripts/travis/$TRAVIS_OS_NAME/$CC/install; fi

script:
- ./autogen.sh
- ./scripts/travis/$TRAVIS_OS_NAME/$CC/configure
- make
- VERBOSE=true make check
