#! /bin/bash
#
# Copyright (C) 2011,13 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
set -e
set -x

build() {
    local arch="$1"
    local chroot="$2"
    local prefix

    if [ "$chroot" = "" ]; then
      prefix=""
    else
      prefix="schroot -pc${chroot} --"
    fi

    tar xf ${archive}
    cd ${dir}
    $prefix fakeroot debian/rules build binary
    cd ..
    mv ${deb_prefix}${package}_${version}_${arch}.deb products/.
    rm -rf ${dir}
}

make distcheck

deb_prefix=rjk-
package=$(awk '/^PACKAGE_NAME =/ { print $3 }' < Makefile)
version=$(awk '/^PACKAGE_VERSION =/ { print $3 }' < Makefile)
dir=${package}-${version}
archive=${package}-${version}.tar.gz

rm -rf products ${dir}
mkdir products
cp ${archive} products/.

build i386 wheezy32
build amd64
ls -l products
