#! /bin/sh
set -e

srcdir=${srcdir:-.}

if ./texttohtml -t -1 /dev/null 2> tmp-bad-tab.got; then
  echo ERROR: unexpected succeeded >&2
  exit 1
fi
echo 'ERROR: invalid tab stop size' > tmp-bad-tab.expect
diff -u tmp-bad-tab.expect tmp-bad-tab.got

rm -f tmp-*.got tmp-*.expect
